// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyAcDuJLiwOkwEKXSnmc-S9bkHDTz-uKBeE","authDomain":"rpg-maker-mz.firebaseapp.com.firebaseapp.com","databaseURL":"https://rpg-maker-mz-default-rtdb.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"20","syncVariableStart":"11","syncVariableEnd":"20"}}
];
